site_name: LSSCB Cluster
site_author: Paweł Rubach
repo_url: https://github.com/prubach/chembio
docs_dir: docs
theme:
  name: material
  logo: "img/logo.png"
  favicon: "img/favicon.ico"
markdown_extensions:
  - admonition:
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
nav:
    - Home: index.md
    - Getting started: first_steps.md
    - Running calculations: running_jobs.md
    - FAQ: faq.md
    - Available resources: resources.md
    - Available software: software.md
    - General rules: rules.md
extra_css:
  - stylesheets/extra.css
